// This file is auto-generated by openapi-typescript
// Run: npm run generate:types

export interface paths {
  "/auth/login": {
    post: {
      requestBody: {
        content: {
          "application/json": LoginRequest
        }
      }
      responses: {
        200: {
          content: {
            "application/json": LoginResponse
          }
        }
        401: {
          content: {
            "application/json": Error
          }
        }
      }
    }
  }
  "/auth/me": {
    get: {
      responses: {
        200: {
          content: {
            "application/json": Researcher
          }
        }
        401: {
          content: {
            "application/json": Error
          }
        }
      }
    }
  }
  "/auth/logout": {
    post: {
      responses: {
        204: {}
        401: {
          content: {
            "application/json": Error
          }
        }
      }
    }
  }
  "/researchers": {
    get: {
      parameters: {
        query: {
          teamId?: number
        }
      }
      responses: {
        200: {
          content: {
            "application/json": Researcher[]
          }
        }
      }
    }
    post: {
      requestBody: {
        content: {
          "application/json": ResearcherCreate
        }
      }
      responses: {
        201: {
          content: {
            "application/json": Researcher
          }
        }
      }
    }
  }
  "/researchers/{id}": {
    get: {
      parameters: {
        path: {
          id: number
        }
      }
      responses: {
        200: {
          content: {
            "application/json": Researcher
          }
        }
        404: {
          content: {
            "application/json": Error
          }
        }
      }
    }
    patch: {
      parameters: {
        path: {
          id: number
        }
      }
      requestBody: {
        content: {
          "application/json": ResearcherUpdate
        }
      }
      responses: {
        200: {
          content: {
            "application/json": Researcher
          }
        }
      }
    }
    delete: {
      parameters: {
        path: {
          id: number
        }
      }
      responses: {
        204: {}
      }
    }
  }
  "/teams": {
    get: {
      responses: {
        200: {
          content: {
            "application/json": Team[]
          }
        }
      }
    }
    post: {
      requestBody: {
        content: {
          "application/json": TeamCreate
        }
      }
      responses: {
        201: {
          content: {
            "application/json": Team
          }
        }
      }
    }
  }
  "/teams/{id}": {
    get: {
      parameters: {
        path: {
          id: number
        }
      }
      responses: {
        200: {
          content: {
            "application/json": Team
          }
        }
        404: {
          content: {
            "application/json": Error
          }
        }
      }
    }
    patch: {
      parameters: {
        path: {
          id: number
        }
      }
      requestBody: {
        content: {
          "application/json": TeamUpdate
        }
      }
      responses: {
        200: {
          content: {
            "application/json": Team
          }
        }
      }
    }
    delete: {
      parameters: {
        path: {
          id: number
        }
      }
      responses: {
        204: {}
      }
    }
  }
  "/teams/{id}/publications": {
    get: {
      parameters: {
        path: {
          id: number
        }
        query: {
          recent?: boolean
          limit?: number
        }
      }
      responses: {
        200: {
          content: {
            "application/json": Publication[]
          }
        }
      }
    }
  }
  "/publications": {
    get: {
      parameters: {
        query: {
          type?: PublicationType
          year?: number
          teamId?: number
          researcherId?: number
        }
      }
      responses: {
        200: {
          content: {
            "application/json": Publication[]
          }
        }
      }
    }
    post: {
      requestBody: {
        content: {
          "application/json": PublicationCreate
        }
      }
      responses: {
        201: {
          content: {
            "application/json": Publication
          }
        }
      }
    }
  }
  "/publications/{id}": {
    get: {
      parameters: {
        path: {
          id: number
        }
      }
      responses: {
        200: {
          content: {
            "application/json": Publication
          }
        }
        404: {
          content: {
            "application/json": Error
          }
        }
      }
    }
    patch: {
      parameters: {
        path: {
          id: number
        }
      }
      requestBody: {
        content: {
          "application/json": PublicationUpdate
        }
      }
      responses: {
        200: {
          content: {
            "application/json": Publication
          }
        }
      }
    }
    delete: {
      parameters: {
        path: {
          id: number
        }
      }
      responses: {
        204: {}
      }
    }
  }
  "/stats/publications-by-year": {
    get: {
      parameters: {
        query: {
          teamId?: number
          researcherId?: number
        }
      }
      responses: {
        200: {
          content: {
            "application/json": StatsByYearItem[]
          }
        }
      }
    }
  }
  "/stats/publications-by-team": {
    get: {
      responses: {
        200: {
          content: {
            "application/json": StatsByGroupItem[]
          }
        }
      }
    }
  }
  "/stats/publications-by-researcher": {
    get: {
      responses: {
        200: {
          content: {
            "application/json": StatsByGroupItem[]
          }
        }
      }
    }
  }
}

export interface Researcher {
  id: number
  name: string
  email: string
  grade: string
  teamId?: number
  role: "admin" | "researcher"
}

export interface ResearcherCreate {
  name: string
  email: string
  password: string
  grade: string
  teamId?: number
  role: "admin" | "researcher"
}

export interface ResearcherUpdate {
  name?: string
  email?: string
  password?: string
  grade?: string
  teamId?: number
  role?: "admin" | "researcher"
}

export interface Team {
  id: number
  name: string
  leadId?: number
  memberCount?: number
}

export interface TeamCreate {
  name: string
  leadId?: number
}

export interface TeamUpdate {
  name?: string
  leadId?: number
}

export type PublicationType = "conference" | "article" | "chapter"

export interface Publication {
  id: number
  title: string
  year: number
  type: PublicationType
  pdfUrl?: string
  teamId?: number
  researcherId?: number
  createdAt?: string
}

export interface PublicationCreate {
  title: string
  year: number
  type: PublicationType
  pdfUrl?: string
  teamId?: number
  researcherId?: number
}

export interface PublicationUpdate {
  title?: string
  year?: number
  type?: PublicationType
  pdfUrl?: string
  teamId?: number
  researcherId?: number
}

export interface LoginRequest {
  email: string
  password: string
}

export interface LoginResponse {
  token: string
  user: Researcher
}

export interface StatsByYearItem {
  year: number
  count: number
}

export interface StatsByGroupItem {
  id: number
  name: string
  count: number
}

export interface Error {
  code?: string
  message: string
}
